baseurl: "" # The subpath of your site. Use "" if you're hosting a blog at the root level.
url: "AkronCodeClub.github.io" # the base hostname & protocol for your site.
title: "Akron Code Club"


paginate: 3 #articles per page
paginate_path: /blog/page:num #makes pagination working


#contacts
git: "https://github.com/AkronCodeClub"  #Add your github url here.
#stackoverflow: "http://stackoverflow.com/users/1231365/railsr" #Add your stackoverflow url here.
stackoverflow: ""
twitter: "https://twitter.com/AkronCodeClub"  #Add your twitter url here.
meetup: "http://www.meetup.com/AkronCodeClub/"

#disqus comment
#disqus:
    #shortname: "test" #replace with your disqus comment short name

#google analytics
#google:
    #tracking-id: "" #paste your tracking id here
gems:
  - jekyll-sitemap

# This is used by feed.xml. Uncomment if you want to use it.
# description: "..."

exclude:
  - "README.md"
  - "CHANGELOG.md"
  - "Gemfile"
  - "Gemfile.lock"
permalink: :title
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
